name: Build

on:
  workflow_call:
    inputs:
      publish:
        description: Publish the image
        default: false
        type: boolean
      image-tag:
        description: The tag of the image
        default: latest
        type: string

  workflow_dispatch:
    inputs:
      publish:
        description: Publish the image
        default: false
        type: boolean
      image-tag:
        description: The tag of the image
        default: latest
        type: string

jobs:
  build:
    runs-on: ${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Download dependencies
        run: go mod download -x

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 1m --verbose
          skip-cache: true

      - name: Build
        run: make build-image IMAGE_TAG=${{ inputs.image-tag }}

      - name: Assume AWS role
        uses: axatol/actions/assume-aws-role@release
        if: inputs.publish
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}

      - name: Login to ECR
        if: inputs.publish
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Publish
        if: inputs.publish
        run: make publish-image IMAGE_TAG=${{ inputs.image-tag }}

      - name: Prune ECR
        if: inputs.publish
        uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: external-dns-cloudflare-tunnel-webhook
