name: On push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".github/**"

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      publish: true
