name: On push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".github/**"

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    permissions:
      contents: read
      id-token: write
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
    with:
      publish: true
